name = "4x8matrix/studio_themer"
version = "0.1.0"
description = "Studio Themer - one command that themes every layer of Roblox Studio, with a terminal wizard."
license = "MIT"
authors = ["Async Matrix <hi@asyncmatrix.dev>"]
repository = "https://github.com/4x8Matrix/studio-themer"
pesde_version = "0.7.3"

includes = [
    "src/**/*",
    "base/**/*",
    "bin.luau",
    "pesde.toml",
    "LICENSE",
    "README.md",
    "patches/**/*",
]

[target]
environment = "luau"
bin = "bin.luau"

[indices]
default = "https://github.com/pesde-pkg/index"

[dependencies]
std_polyfills = { name = "discord_luau/std_polyfills", version = ">=0.0.0" }
logger = { name = "discord_luau/logger", version = ">=0.0.0" }
cli_builder = { name = "4x8matrix/cli_builder", version = "0.2.1" }

[patches]
"discord_luau/std_polyfills" = { "0.0.3 luau" = "patches/discord_luau+std_polyfills-0.0.3+luau.patch" }
